version: '3'
services:

  #PHP Service
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: drupal8-php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: drupal8-webserver
    restart: always
    tty: true
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    networks:
      - app-network

  #MySQL Service
  dbsever:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: drupal8-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_user: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "drupal8"
      MYSQL_PASSWORD: "drupal8"
      MYSQL_DATABASE: "drupal8"
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge